# Generated by Django 3.2.9 on 2021-11-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
