# Generated by Django 3.2.9 on 2021-11-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ledger_save',
            new_name='LedgerSave',
        ),
    ]
