# Generated by Django 3.2.9 on 2021-11-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
